#!/bin/bash
#
# COMPARE GAUSSIAN NONSTANDARD ROUTES
#
# Usage
  if [ $# -ne 2 ]; then echo 'Usage: compgau td cis'; exit 1; fi
# Must have the testrt utility
  if [ ! -x "$( which testrt )" ]; then echo 'ERROR: testrt utility not found, is Gaussian defined?'; exit 1; fi
# Build commands
  route1="$( mktemp )"; route2="$( mktemp )"
  testrt "${1}" > "${route1}"
  testrt "${2}" > "${route2}"
  vimdiff "${route1}" "${route2}"
# Delete temporary files
  rm -- "${route1}" "${route2}"
